package switchboard

// llms.txt is generated by docs-site/scripts/build-docs.mjs. The docs build in
// .gitea/workflows/docs.yaml is advisory and path-filtered, and it does not check absolute URLs, so
// a hand-typed llms.txt route that no longer matches its source file builds green and 404s for
// every agent that follows it. This runs in the required go test gate instead: it checks each docs
// link against docs/<section>/NN-<slug>.md and proves the private-host guard fires. The script uses
// only node builtins, so it runs against a scratch copy of docs/ and never touches docs-site/.
// Governing: issue #340 (publish llms.txt and a paste-to-your-agent block).

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

const llmsDocsURL = "https://switchboard.stump.wtf"

// runBuildDocs copies docs/ and build-docs.mjs into a scratch tree shaped like the repo, runs the
// script with DOCS_URL set, and returns the scratch docs-site dir, the combined output, and the
// run error.
func runBuildDocs(t *testing.T, docsURL string) (string, string, error) {
	t.Helper()
	node, err := exec.LookPath("node")
	if err != nil {
		msg := "WARNING: SKIPPED " + t.Name() + " — node not found in PATH: the llms.txt generator DID NOT RUN. " +
			"Install Node.js 20+ so this gate executes; this skip must never be treated as a pass."
		fmt.Fprintln(os.Stderr, msg)
		t.Skip(msg)
	}
	root := t.TempDir()
	if err := os.CopyFS(filepath.Join(root, "docs"), os.DirFS("docs")); err != nil {
		t.Fatalf("copy docs/: %v", err)
	}
	site := filepath.Join(root, "docs-site")
	for _, d := range []string{"scripts", "static"} {
		if err := os.MkdirAll(filepath.Join(site, d), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	script, err := os.ReadFile("docs-site/scripts/build-docs.mjs")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(site, "scripts", "build-docs.mjs"), script, 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(node, filepath.Join(site, "scripts", "build-docs.mjs"))
	cmd.Env = append(os.Environ(), "DOCS_URL="+docsURL)
	out, err := cmd.CombinedOutput()
	return site, string(out), err
}

// frontmatterTitle returns the `title:` value from a docs source file's front matter, the same
// field build-docs.mjs reads.
func frontmatterTitle(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	m := regexp.MustCompile(`(?m)\A---\n(?:.*\n)*?title:[ \t]*(.+?)[ \t]*\n(?:.*\n)*?---\n`).FindSubmatch(b)
	if m == nil {
		return ""
	}
	return string(m[1])
}

func TestLLMSTxtLinksResolveToSourcePages(t *testing.T) {
	site, out, err := runBuildDocs(t, llmsDocsURL)
	if err != nil {
		t.Fatalf("build-docs.mjs failed: %v\n%s", err, out)
	}
	b, err := os.ReadFile(filepath.Join(site, "static", "llms.txt"))
	if err != nil {
		t.Fatalf("build-docs.mjs did not write static/llms.txt: %v", err)
	}
	llms := string(b)

	// llmstxt.org shape: an H1 first, then a blockquote summary.
	if !strings.HasPrefix(llms, "# Switchboard\n\n> ") {
		t.Errorf("llms.txt must open with an H1 and a blockquote summary; got:\n%s", llms)
	}
	if strings.Contains(llms, "stump.rocks") {
		t.Errorf("llms.txt names a private stump.rocks host:\n%s", llms)
	}

	entry := regexp.MustCompile(`^- \[([^\]]+)\]\((https://[^)\s]+)\): \S`)
	docsRoot := llmsDocsURL + "/docs/"
	section, entries, docsLinks := "", 0, 0
	sc := bufio.NewScanner(strings.NewReader(llms))
	for sc.Scan() {
		line := sc.Text()
		if h, ok := strings.CutPrefix(line, "## "); ok {
			section = h
			continue
		}
		if !strings.HasPrefix(line, "- ") {
			continue
		}
		m := entry.FindStringSubmatch(line)
		if m == nil {
			t.Errorf("malformed llms.txt entry (want `- [Title](https://…): note`): %q", line)
			continue
		}
		entries++
		title, url := m[1], m[2]
		if section == "Start here" && !strings.HasSuffix(url, "/getting-started/connect-an-agent") {
			t.Errorf("Start here should point at the connect page, got %s", url)
		}
		route, ok := strings.CutPrefix(url, docsRoot)
		if !ok {
			continue // an external page (the Harness stack guide)
		}
		docsLinks++
		// A docs route is <section>/<slug>, served from docs/<section>/NN-<slug>.md.
		dir, slug, ok := strings.Cut(route, "/")
		if !ok || strings.Contains(slug, "/") {
			t.Errorf("unexpected docs route %q in %q", route, line)
			continue
		}
		srcs, _ := filepath.Glob(filepath.Join("docs", dir, "[0-9]*-"+slug+".md"))
		if len(srcs) != 1 {
			t.Errorf("%s: no single source page docs/%s/NN-%s.md (found %v), so the link 404s", url, dir, slug, srcs)
			continue
		}
		if want := frontmatterTitle(t, srcs[0]); title != want {
			t.Errorf("%s: llms.txt title %q, but %s's front-matter title is %q", url, title, srcs[0], want)
		}
	}
	if entries == 0 || docsLinks == 0 {
		t.Fatalf("llms.txt has %d entries (%d docs links); want at least one of each:\n%s", entries, docsLinks, llms)
	}

	// The paste block on the connect page sends agents to this file; both halves must agree.
	page, err := os.ReadFile("docs/getting-started/03-connect-an-agent.md")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(page), docsRoot+"llms.txt") {
		t.Errorf("the connect page's paste block no longer points agents at %sllms.txt", docsRoot)
	}
}

func TestLLMSTxtRefusesPrivateHost(t *testing.T) {
	site, out, err := runBuildDocs(t, "https://switchboard.pages.stump.rocks")
	if err == nil {
		t.Fatalf("build-docs.mjs succeeded with a private DOCS_URL; the stump.rocks guard did not fire:\n%s", out)
	}
	if !strings.Contains(out, "private host (switchboard.pages.stump.rocks)") {
		t.Errorf("build-docs.mjs failed, but not with the private-host guard:\n%s", out)
	}
	if _, statErr := os.Stat(filepath.Join(site, "static", "llms.txt")); statErr == nil {
		t.Error("static/llms.txt was written even though the private-host guard fired")
	}
}
