// @ts-check
// Docusaurus config for the switchboard docs site.
// Renders getting started (docs/getting-started), the user guides (docs/guides), ADRs (docs/adrs),
// OpenSpec specs (docs/openspec/specs), design language (docs/design), and reference contracts
// (docs/reference) — transformed into docs-generated/ by scripts/build-docs.mjs at build time — plus
// a per-endpoint HTTP API reference generated from docs/reference/openapi.yaml by
// docusaurus-plugin-openapi-docs, all with mermaid diagrams and the switchboard-era theme.
//
// Served as compiled static files by the front Caddy at https://switchboard.stump.wtf/docs/
// (baseUrl /docs/). The site is public and the source repository is not, so nothing here links to
// the repository.
//
// The marketing landing page is src/pages/index.mdx (a standalone page — NO docs sidebar). The
// design-record docs (guides/decisions/specs/design/reference) mount at routeBasePath '/', and the
// generated HTTP API reference mounts as a SECOND docs instance at /api so its per-endpoint pages
// stay out of the main autogenerated sidebar.

const { themes } = require('prism-react-renderer');

const SITE_URL = process.env.DOCS_URL || 'https://switchboard.stump.wtf';
const BASE_URL = '/docs/';

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Switchboard',
  tagline: 'The operator’s board for inbound webhooks — receive, verify, patch through.',
  favicon: 'img/favicon.svg',

  future: { v4: true },

  url: SITE_URL,
  baseUrl: BASE_URL,
  organizationName: 'stump-wtf',
  projectName: 'switchboard',

  // A broken link fails the build, so the pull-request docs build (.gitea/workflows/docs.yaml)
  // catches it before merge rather than after (issue 245, SPEC-0027 REQ-12).
  onBrokenLinks: 'throw',

  // MDX everywhere (default) so mermaid ```mermaid blocks in the ADRs render as diagrams. The
  // build script sanitizes the one MDX-hostile construct in the source (autolinks) — see build-docs.mjs.
  markdown: { mermaid: true, hooks: { onBrokenMarkdownLinks: 'throw' } },
  themes: [
    '@docusaurus/theme-mermaid',
    // Renders the per-endpoint API pages generated by docusaurus-plugin-openapi-docs (ApiItem).
    'docusaurus-theme-openapi-docs',
  ],

  i18n: { defaultLocale: 'en', locales: ['en'] },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'docs-generated',
          routeBasePath: '/',
          sidebarPath: require.resolve('./sidebars.js'),
          // The API instance renders per-operation pages with the OpenAPI theme's ApiItem; the main
          // instance keeps the stock DocItem for guides/decisions/specs/design/reference.
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  plugins: [
    // Second docs instance: the generated per-endpoint HTTP API reference at /api. Its content is
    // written to ./api-docs by `docusaurus gen-api-docs` (see the openapi-docs plugin below), which
    // runs in the prestart/prebuild npm hooks before Docusaurus loads. docItemComponent ApiItem
    // gives each operation the request/response schema explorer + try-it console.
    [
      '@docusaurus/plugin-content-docs',
      /** @type {import('@docusaurus/plugin-content-docs').Options} */
      ({
        id: 'api',
        path: 'api-docs',
        routeBasePath: 'api',
        sidebarPath: './sidebars.api.ts',
        docItemComponent: '@theme/ApiItem',
      }),
    ],
    // Generates the api-docs/ MDX + sidebar from the hand-authored OpenAPI 3.1 contract.
    [
      'docusaurus-plugin-openapi-docs',
      /** @type {import('docusaurus-plugin-openapi-docs').PluginOptions} */
      ({
        id: 'openapi',
        docsPluginId: 'api',
        config: {
          switchboard: {
            specPath: '../docs/reference/openapi.yaml',
            outputDir: 'api-docs',
            downloadUrl: '/docs/reference/openapi.yaml',
            sidebarOptions: {
              groupPathsBy: 'tag',
              categoryLinkSource: 'tag',
            },
            hideSendButton: false,
          },
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: { defaultMode: 'dark', respectPrefersColorScheme: true },
      navbar: {
        title: 'Switchboard',
        logo: { alt: 'Switchboard jack', src: 'img/logo.svg' },
        items: [
          { type: 'docSidebar', sidebarId: 'docs', position: 'left', label: 'Guides' },
          { type: 'docSidebar', docsPluginId: 'api', sidebarId: 'apiSidebar', position: 'left', label: 'API' },
          { to: '/decisions', label: 'Decisions', position: 'left' },
          { to: '/specs', label: 'Specs', position: 'left' },
          { to: '/design', label: 'Design', position: 'left' },
          { to: '/prfaq', label: 'PRFAQ', position: 'left' },
          { href: 'https://switchboard.stump.wtf', label: 'Open the board', position: 'right' },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Use',
            items: [
              { label: 'Getting started', to: '/getting-started/concepts' },
              { label: 'Guides', to: '/guides/overview' },
              { label: 'Troubleshooting', to: '/guides/troubleshooting' },
              { label: 'API', to: '/api' },
            ],
          },
          {
            title: 'Design record',
            items: [
              { label: 'PRFAQ', to: '/prfaq' },
              { label: 'Decisions (ADRs)', to: '/decisions' },
              { label: 'Specifications', to: '/specs' },
              { label: 'Design', to: '/design' },
              { label: 'Reference', to: '/reference' },
            ],
          },
          {
            title: 'Related',
            items: [
              { label: 'Harness', href: 'https://stump-wtf.github.io/harness/' },
              { label: 'Cairn', href: 'https://cairn.stump.wtf/docs/' },
            ],
          },
        ],
        copyright: `Switchboard — © 2026 Joe Stump. MIT. “Many lines come in; the operator patches each through.”`,
      },
      prism: {
        theme: themes.oneLight,
        darkTheme: themes.oneDark,
        additionalLanguages: ['bash', 'json', 'yaml', 'python', 'toml'],
      },
      mermaid: { theme: { light: 'neutral', dark: 'dark' } },
    }),
};

module.exports = config;
