// Sidebar is auto-generated from the docs-generated/ tree (sidebar_position + _category_.json),
// which scripts/build-docs.mjs produces from docs/adrs, docs/openspec/specs, and docs/reference.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
